cygnet/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from projects.views import index, user_login, user_logout

urlpatterns = [
    path('admin/', admin.site.urls),
    path('files/', include('files.urls', namespace='files')),
    path('projects/', include('projects.urls', namespace='projects')),
    path('', index, name="home"),
    path('login/', user_login, name="login"),
    path('logout/', user_logout, name="logout")
]
if settings.DEBUG:
    urlpatterns = urlpatterns + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns = urlpatterns + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

files/urls.py
from django.urls import path
from .views import *

app_name = 'files'

urlpatterns = [
    ## Files ##
    path('upload', upload, name='upload'),
    path('dds_upload', dds_upload, name='dds_upload'),
    path('dtf_upload', dtf_upload, name='dtf_upload'),
    ## DDS ##
    path('dds/<int:pk>/', DDSDetailView.as_view(), name="dds"),
    path('dds/export/', export_dds, name="dds_export"),
    path('dds/dds_mappings_export/', mapping_export, name="dds_mappings_export"),
    path('dds/export_cmds/', mapping_export_with_regs, name="export_cmds"),
    path('dds/dds_add_mappings/', dds_add_mapping, name="dds_add_mappings"),
    path('dds/dds_add_commands/', dds_add_commands, name="dds_add_commands"),
    path('dds/correct_dec_check/', correct_device_check, name="correct_dec_check"),
    path('dds/unmapped_facs/', unmapped_facs, name="unmapped_facs"),
    path('dds/orphans/', find_orphans, name="orphans"),
    path('dds/fac_exist/', facs_dne, name="fac_exist"),
    path('dds/validate_commands/', validate_commands, name="validate_commands"),
    path('dds/get_mappings/', get_mappings, name="get_mappings"),
    path('dds/delete/', dds_delete, name="dds_delete"),
    path('dds/validate_maps/', validate_mappings, name="validate_maps"),
    path('dds/import_facs/', import_facs, name="import_facs"),
    ## DTF ##
    path('dtf/<int:pk>/', DTFDetailView.as_view(), name="dtf"),
    path('dtf/export/', export_dtf, name='dtf_export'),
    path('dtf/unused_deids/', unmapped_dieds, name="unused_dieds"),
    path('dtf/delete/', dtf_delete, name="dtf_delete"),
    path('dtf/export_dtf_data/', export_dtf_data, name="export_dtf_data"),
    path('dtf/generic_dtf_data/', generic_dtf_data, name="generic_dtf_data"),
    path('dtf/add_array/', add_array, name="add_array"),
    path('dtf/import_arrays/', import_arrays, name="import_arrays"),
    path('dtf/dtf_dg_import/', dtf_data_group_import, name="dtf_dg_import"),
    path('dtf/dtf_dg_modbus_import/', dtf_data_group_modbus_import, name="dtf_dg_import_modbus"),
    path('dtf/delete_datagroup/', delete_datagroup, name="delete_datagroup"),
    ## TEMPLATES ##
    path('dds/mapping_template/', mapping_template, name="mapping_template"),
    path('dds/mapping_validation_template/', mapping_validation_template, name="mapping_validation_template"),
    path('dds/commands_template/', command_import_template, name="command_template"),
    path('dds/commands_validation_template/', command_validation_template, name="command_validation_template"),
    path('dds/facility_import_template/', facility_import_template, name="facility_import_template"),
]

files/forms.py
from django import forms
from .models import DDS, DTF


class DDSForm(forms.ModelForm):
    class Meta:
        model = DDS
        fields = ('project', 'file',)
        widgets = {'project': forms.HiddenInput()}


class DTFForm(forms.ModelForm):
    class Meta:
        model = DTF
        fields = ('project', 'file',)
        widgets = {'project': forms.HiddenInput()}

files/views.py
from django.shortcuts import render, redirect
from django.http import JsonResponse, HttpResponseRedirect
from django.template.loader import render_to_string
from django.views.generic import DetailView
from django.http import HttpResponse, Http404
from django.conf import settings
from django.core.exceptions import ObjectDoesNotExist
from django.views.decorators.csrf import csrf_exempt

from .models import DDS, DTF
from .forms import DDSForm, DTFForm
from .utils import build_ajax_response_dict

import os
from cygdevices.device import DeviceDef

import pandas as pd


def upload(request):
    cont_dict = {
        "dds_form": DDSForm,
        "dtf_form": DTFForm,
    }
    return render(request, 'files/file_upload.html', cont_dict)


def dds_upload(request):
    if request.method == 'POST':
        form = DDSForm(request.POST, request.FILES)
        next = request.POST.get('next', '/')
        if form.is_valid():
            form.save()
        else:
            print("Error in form")
    return redirect(next)


def dds_delete(request):
    dds_id = request.GET.get("id")
    try:
        dds = DDS.objects.get(pk=int(dds_id))
    except ObjectDoesNotExist:
        return redirect("files:upload")
    dds.delete()
    return HttpResponseRedirect(request.META.get('HTTP_REFERER', '/'))


class DDSDetailView(DetailView):
    queryset = DDS.objects.all()

    def get_context_data(self, **kwargs):
        data = super().get_context_data(**kwargs)
        proj = self.object.project
        data['dtfs'] = DTF.objects.filter(project=proj)
        data['project'] = proj
        try:
            data['devices'] = self.object.xml.all_devices()
        except:
            return data
        return data


def export_dds(request):
    dds_id = request.GET.get("id")
    try:
        dds = DDS.objects.get(pk=dds_id)
        file_path = os.path.join(settings.MEDIA_ROOT, str(dds.file))
        response = HttpResponse(dds.xml.pretty_print(), content_type='application/force-download')
        response['Content-Disposition'] = 'attachment; filename=' + os.path.basename(file_path)
        response['X-Sendfile'] = file_path
    except:
        raise Http404
    return response


def dds_add_mapping(request):
    # Pass Excel file and dtf document to import script, return error logs
    if request.method == "POST":
        mappings = request.FILES["mappings"]
        deid_only = True if "deid-only" in request.POST else False
        try:
            dtf = DTF.objects.get(pk=int(request.POST.get("dtf-id")))
            dds = DDS.objects.get(pk=int(request.POST.get("dds-id")))
        except ObjectDoesNotExist:
            print("DTF or DDS not found")
            return redirect("files:upload")
        try:
            errors = dds.add_mappings(dtf, mappings, deid_only)
        except:
            errors = ["Error Handling Excel File. Please use template file", ]
        if request.is_ajax():
            errs = []
            for e in errors:
                errs.append({"Log": e})
            data = build_ajax_response_dict(errs, "Import Log")
            devices = dds.xml.all_devices()
            devices_html = render_to_string("files/snippets/device_accord.html", {"devices": devices})
            data["devices_html"] = devices_html
            return JsonResponse(data)
    return redirect("files:upload")


def mapping_export(request):
    dds_id = request.GET.get("id")
    try:
        dds = DDS.objects.get(pk=dds_id)
    except ObjectDoesNotExist:
        print("DTF or DDS not found")
        return redirect("files:upload")
    workbook = dds.xml.export_mappings()
    response = HttpResponse(workbook, content_type='application/vnd.openxmlformats-officedocument.spreadsheetml.sheet')
    response['Content-Disposition'] = 'attachment; filename={}'.format("dds_mappings_export.xlsx")
    return response


def mapping_export_with_regs(request):
    dds_id = request.POST.get("dds-id")
    dtf_id = request.POST.get("dtf-id")
    try:
        dds = DDS.objects.get(pk=int(dds_id))
        dtf = DTF.objects.get(pk=int(dtf_id))
    except ObjectDoesNotExist:
        print("DTF or DDS not found")
        return redirect("files:upload")
    workbook = dds.xml.export_mappings(dtf.xml)
    response = HttpResponse(workbook, content_type='application/vnd.openxmlformats-officedocument.spreadsheetml.sheet')
    response['Content-Disposition'] = 'attachment; filename={}'.format("dds_mappings_export.xlsx")
    return response


@csrf_exempt
def correct_device_check(request):
    dds_id = request.POST.get("id")
    try:
        dds = DDS.objects.get(pk=dds_id)
    except ObjectDoesNotExist:
        print("DTF or DDS not found")
        return redirect("files:upload")
    non_matches = dds.xml.correct_dev_check()
    if request.is_ajax():
        data = build_ajax_response_dict(non_matches, "Wrong Device")
        return JsonResponse(data)
    return redirect("files:upload")


@csrf_exempt
def unmapped_facs(request):
    if request.method == "POST":
        dds_xml = DDS.objects.get(pk=int(request.POST.get("id"))).xml
        map_facs = request.POST.get("map")
        unmapped = dds_xml.mapped_fac_check()
        if map_facs:
            log = []
            for f in unmapped:
                outcome = dds_xml.add_facility(f["facility"], f["device"])
                log.append({"outcome": outcome})
            data = build_ajax_response_dict(log, "Facility Added Outcomes")
            devices = dds_xml.all_devices()
            dds_xml.save()
            devices_html = render_to_string("files/snippets/device_accord.html", {"devices": devices})
            data["devices_html"] = devices_html
            return JsonResponse(data)
        else:
            data = build_ajax_response_dict(unmapped, "Unmapped Facilities")
            return JsonResponse(data)
    if request.method == "GET":
        dds_id = request.GET.get("id")
        try:
            dds = DDS.objects.get(pk=dds_id)
        except ObjectDoesNotExist:
            print("DTF or DDS not found")
            return redirect("files:upload")
        unmapped = dds.xml.mapped_fac_check()
        if request.is_ajax():
            data = build_ajax_response_dict(unmapped, "Unmapped Facilities")
            return JsonResponse(data)
    return redirect("files:upload")


def find_orphans(request):
    if request.method == "POST":
        try:
            dtf = DTF.objects.get(pk=int(request.POST.get("dtf-id"))).xml
            dds = DDS.objects.get(pk=int(request.POST.get("dds-id"))).xml
        except ObjectDoesNotExist:
            print("DTF or DDS not found")
            return redirect("files:upload")
        if dtf is not None and dds is not None:
            orphans = dds.find_orphans(dtf)
        else:
            orphans = [{"ERROR": "DDS or DTF file not found"}]
        if request.is_ajax():
            if request.is_ajax():
                data = build_ajax_response_dict(orphans, "Orphans")
                return JsonResponse(data)
    return redirect("files:upload")


def facs_dne(request):
    if request.method == "POST":
        if "facs" not in request.FILES:
            return JsonResponse({"error": True})
        facs = request.FILES["facs"] if "facs" in request.FILES else None
        try:
            dds = DDS.objects.get(pk=int(request.POST.get("dds-id")))
        except ObjectDoesNotExist:
            print("DTF or DDS not found")
            return redirect("files:upload")
        dne = dds.check_facilities(facs)
        if request.is_ajax():
            data = build_ajax_response_dict(dne, "Non Existent Facs")
            return JsonResponse(data)
    return redirect("files:upload")


def validate_commands(request):
    if request.method == "POST":
        if "cmds" not in request.FILES:
            return JsonResponse({"error": True})
        cmd_data = request.FILES["cmds"] if "cmds" in request.FILES else None
        try:
            dds = DDS.objects.get(pk=int(request.POST.get("dds-id")))
            dtf = DTF.objects.get(pk=int(request.POST.get("dtf-id")))
        except ObjectDoesNotExist:
            print("DTF or DDS not found")
            return redirect("files:upload")
        errors = dds.validate_cmds(cmd_data, dtf)
        if request.is_ajax():
            data = build_ajax_response_dict(errors, "Command Errors")
            return JsonResponse(data)
    return redirect("files:upload")


@csrf_exempt
def get_mappings(request):
    if request.method == "POST":
        data_group = request.POST.get("data_group")
        device = request.POST.get("device")
        try:
            dds = DDS.objects.get(pk=int(request.POST.get("id"))).xml
        except ObjectDoesNotExist:
            print("DTF or DDS not found")
            return redirect("files:upload")
        maps = dds.all_mappings(device, data_group)
        if request.is_ajax():
            data = build_ajax_response_dict(maps, "All Mappings")
            return JsonResponse(data)
    return redirect("home")


def validate_mappings(request):
    if request.method == "POST":
        if "pnts" not in request.FILES:
            return JsonResponse({"error": True})
        pnt_data = request.FILES["pnts"]
        try:
            dds = DDS.objects.get(pk=int(request.POST.get("dds-id")))
            dtf = DTF.objects.get(pk=int(request.POST.get("dtf-id"))).xml
        except ObjectDoesNotExist:
            print("DTF or DDS not found")
            return redirect("files:upload")
        errors = dds.validate_mappings(dtf, pnt_data)
        if request.is_ajax():
            data = build_ajax_response_dict(errors, "Mapping Errors")
            return JsonResponse(data)
    return redirect("files:upload")


def mapping_template(reqeust):
    workbook = DeviceDef.mappings_template()
    response = HttpResponse(workbook, content_type='application/vnd.openxmlformats-officedocument.spreadsheetml.sheet')
    response['Content-Disposition'] = 'attachment; filename={}'.format("Mappings_import_template.xlsx")

files/templates/files/dds.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <link rel="stylesheet" href="//cdnjs.cloudflare.com/ajax/libs/highlight.js/9.15.8/styles/default.min.css">
    <script src="//cdnjs.cloudflare.com/ajax/libs/highlight.js/9.15.8/highlight.min.js"></script>

</head>
<body>
{% if file_strs %}
{% for f in file_strs %}
<p>{{ f }}</p>
{% endfor %}
{% endif %}
<pre><code class="xml hljs">{{ code_string }}</code></pre>
</body>

</html>

files/templates/files/dtf_detail.html
{% extends 'base.html' %}
{% block body_block %}
<div class="container">
    <div class="row file-header">
        <h2>{{ dtf.base_file }}</h2>
        <ul>
            <li>Project - {{ dtf.project }}</li>
            <li>Uploaded - {{ dtf.uploaded }}</li>
        </ul>
        <button onclick="window.location.href = '{% url 'files:dtf_export' %}?id={{ dtf.pk }}';">Export File!</button>
        <button onclick="window.location.href = '{% url 'files:export_dtf_data' %}?id={{ dtf.pk }}';">Export Data to
            Excel!
        </button>
        <button onclick="window.location.href = '{% url 'files:generic_dtf_data' %}?id={{ dtf.pk }}';">Generic Excel Export
        </button>
    </div>
    <div class="row">
        <div class="col-sm-8">
            <form method="post" action="{% url 'files:unused_dieds' %}"
                  id="dtf-died-check">
                {% csrf_token %}
                <label>Find Unused DEIDs</label>
                <select name="dds-id">
                    {% if ddss %}
                    {% for dds in ddss %}
                    <option value="{{ dds.pk }}">{{ dds.file }}</option>
                    {% endfor %}
                    {% endif %}
                </select><br>
                <input hidden name="dtf-id" value="{{ dtf.pk }}">
                <button type="submit">Find</button>
            </form>
            <div class="card mb-3 text-center">
                <div class="card-header">
                    <h2>Add New Array</h2>
                </div>
                <div class="card-body">
                    <form method="post" action="{% url 'files:add_array' %}" id="dtf-add-array">
                        {% csrf_token %}
                        <input hidden name="dtf-id" value="{{ dtf.pk }}">
                        <div class="form-group row">
                            <label for="arrayName" class="col-sm-4 col-form-label">Array Name</label>
                            <div class="col-sm-8">
                                <input type="text" class="form-control" id="arrayName" name="arrayName"
                                       placeholder="DI_ARRAY">
                            </div>
                        </div>
                        <div class="form-group row">
                            <label for="niceName" class="col-sm-4 col-form-label">Nice Name</label>
                            <div class="col-sm-8">
                                <input type="text" class="form-control" id="niceName" name="niceName"
                                       placeholder="niceName">
                            </div>
                        </div>
                        <div class="form-group row">
                            <label for="tagName" class="col-sm-4 col-form-label">Tag Name</label>
                            <div class="col-sm-8">
                                <input type="text" class="form-control" id="tagName" name="tagName"
                                       placeholder="DI_N40">
                            </div>
                        </div>
                        <div class="form-group row">
                            <label for="dataType" class="col-sm-4 col-form-label">Data Type</label>
                            <div class="col-sm-8">
                                <input type="text" class="form-control" id="dataType" name="dataType" placeholder="r4">
                            </div>
                        </div>
                        <div class="form-group row">
                            <label for="dataType" class="col-sm-4 col-form-label">DEID Naming</label>
                            <div class="col-sm-8">
                                <input type="text" class="form-control" id="deid" name="deid" placeholder="DIArr">
                            </div>
                        </div>
                        <fieldset class="form-group">
                            <div class="row">
                                <legend class="col-form-label col-sm-4 pt-0">Array type</legend>
                                <div class="col-sm-8">
                                    <div class="form-check">
                                        <input class="form-check-input" type="radio" name="diai" id="ai" value="ai"
                                               checked>
                                        <label class="form-check-label" for="ai">Analog</label>
                                    </div>
                                    <div class="form-check">
                                        <input class="form-check-input" type="radio" name="diai" id="di" value="di">
                                        <label class="form-check-label" for="di">Digital</label>
                                    </div>
                                </div>
                            </div>
                        </fieldset>
                        <div class="form-group row">
                            <label for="bits" class="col-sm-4 col-form-label">Bit Numbers</label>
                            <div class="col-sm-8">
                                <select id="bits" class="form-control" name="bits">
                                    <option value="32" selected>32</option>
                                    <option value="16">16</option>
                                </select>
                            </div>
                        </div>
                        <div class="form-group row">
                            <label for="dataType" class="col-sm-4 col-form-label">Start-Stop</label>
                            <div class="col-sm-4">
                                <input type="number" class="form-control" id="start" name="start" value="0">
                            </div>
                            <div class="col-sm-4">
                                <input type="number" class="form-control" id="stop" name="stop" value="5">
                            </div>
                        </div>
                        <div class="form-group row">
                            <div class="col-sm-10">
                                <button type="submit" class="btn btn-primary">Create</button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
            <div class="card mb-3 text-center">
                <div class="card-header">
                    <h2>Import Datagroups from Excel</h2>
                </div>
                <div class="card-body">
                    <form method="post" enctype="multipart/form-data"
                          action="{% url 'files:import_arrays' %}" id="dtf-import-array">
                        {% csrf_token %}
                        <input hidden name="dtf-id" value="{{ dtf.pk }}">
                        <div class="form-group row">
                            <div class="col-sm-12 text-center">
                                <a href="{% url 'files:dtf_dg_import' %}">Download Excel Import Template</a>
                            </div>
                            <div class="col-sm-12 text-center">
                                <a href="{% url 'files:dtf_dg_import_modbus' %}">Download Modbus Excel Import Template</a>
                            </div>
                        </div>
                         <div class="form-group row">
                            <label for="dg-data" class="col-sm-4 col-form-label">Import Excel</label>
                            <div class="col-sm-8">
                                <input type="file" class="form-control" id="dg-data" name="dg-data">
                            </div>
                        </div>
                        <div class="form-group row">
                            <label for="modbus" class="col-sm-4 col-form-label">Modbus?</label>
                            <div class="col-sm-8">
                                <input type="checkbox" class="form-control" id="modbus" name="modbus">
                            </div>
                        </div>
                        <div class="form-group row">
                            <label for="reg-gap" class="col-sm-4 col-form-label">Max Reg Gap for Block</label>
                            <div class="col-sm-8">
                                <input type="number" class="form-control" id="reg-gap" name="reg-gap" value="1">
                            </div>
                        </div>

                        <div class="form-group row">
                            <div class="col-sm-10">
                                <button type="submit" class="btn btn-primary">Create</button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
            <div class="card mb-3 text-center">
                <div class="card-header">
                    <h2>Import String Enumerations from Excel</h2>
                </div>
                <div class="card-body">
                    <form method="post" enctype="multipart/form-data" id="dtf-import-enums">
                        {% csrf_token %}
                        <input hidden name="dtf-id" value="{{ dtf.pk }}">
                        <div class="form-group row">
                            <div class="col-sm-12 text-center">
                                <a href="{% url 'files:dtf_dg_import' %}">Download Excel Import Template</a>
                            </div>
                        </div>
                         <div class="form-group row">
                            <label for="dg-data2" class="col-sm-4 col-form-label">Import Excel</label>
                            <div class="col-sm-8">
                                <input type="file" class="form-control" id="dg-data2" name="dg-data">
                            </div>
                        </div>
                        <div class="form-group row">
                            <div class="col-sm-10">
                                <button type="submit" class="btn btn-primary">Create</button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
        <div class="col-sm-4" id="device-info">
            {% if arrays %}
            {% include 'files/snippets/dtf_arrays.html' with arrays=arrays dtf=dtf %}
            {% endif %}
        </div>
    </div>
    <div class="modal fade" id="response-modal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLongTitle"
         aria-hidden="true">
        <div class="modal-dialog modal-lg" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="exampleModalLongTitle">Response Data</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body" id="modal-body">
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

files/templates/files/dtf_upload.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
    <h1>Upload DDS</h1>
    <form method="post" enctype="multipart/form-data" action="{% url 'files:dds_upload' %}">
        {% csrf_token %}
        {{ dds_form.as_p }}
        <button type="submit">Upload</button>
    </form>
    <h1>Upload DTF</h1>
    <form method="post" enctype="multipart/form-data" action="{% url 'files:dtf_upload' %}">
        {% csrf_token %}
        {{ dtf_form.as_p }}
        <button type="submit">Upload</button>
    </form>
</body>
</html>

files/templates/files/file_upload.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
    <h1>Upload DDS</h1>
    <form method="post" enctype="multipart/form-data" action="{% url 'files:dds_upload' %}">
        {% csrf_token %}
        {{ dds_form.as_p }}
        <button type="submit">Upload</button>
    </form>
    <h1>Upload DTF</h1>
    <form method="post" enctype="multipart/form-data" action="{% url 'files:dtf_upload' %}">
        {% csrf_token %}
        {{ dtf_form.as_p }}
        <button type="submit">Upload</button>
    </form>
</body>
</html>