cygnet/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from projects.views import index, user_login, user_logout

urlpatterns = [
    path('admin/', admin.site.urls),
    path('files/', include('files.urls', namespace='files')),
    path('projects/', include('projects.urls', namespace='projects')),
    path('', index, name="home"),
    path('login/', user_login, name="login"),
    path('logout/', user_logout, name="logout")
]
if settings.DEBUG:
    urlpatterns = urlpatterns + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns = urlpatterns + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

files/urls.py
from django.urls import path
from .views import *

app_name = 'files'

urlpatterns = [
    ## Files ##
    path('upload', upload, name='upload'),
    path('dds_upload', dds_upload, name='dds_upload'),
    path('dtf_upload', dtf_upload, name='dtf_upload'),
    ## DDS ##
    path('dds/<int:pk>/', DDSDetailView.as_view(), name="dds"),
    path('dds/export/', export_dds, name="dds_export"),
    path('dds/dds_mappings_export/', mapping_export, name="dds_mappings_export"),
    path('dds/export_cmds/', mapping_export_with_regs, name="export_cmds"),
    path('dds/dds_add_mappings/', dds_add_mapping, name="dds_add_mappings"),
    path('dds/dds_add_commands/', dds_add_commands, name="dds_add_commands"),
    path('dds/correct_dec_check/', correct_device_check, name="correct_dec_check"),
    path('dds/unmapped_facs/', unmapped_facs, name="unmapped_facs"),
    path('dds/orphans/', find_orphans, name="orphans"),
    path('dds/fac_exist/', facs_dne, name="fac_exist"),
    path('dds/validate_commands/', validate_commands, name="validate_commands"),
    path('dds/get_mappings/', get_mappings, name="get_mappings"),
    path('dds/delete/', dds_delete, name="dds_delete"),
    path('dds/validate_maps/', validate_mappings, name="validate_maps"),
    path('dds/import_facs/', import_facs, name="import_facs"),
    ## DTF ##
    path('dtf/<int:pk>/', DTFDetailView.as_view(), name="dtf"),
    path('dtf/export/', export_dtf, name='dtf_export'),
    path('dtf/unused_deids/', unmapped_dieds, name="unused_dieds"),
    path('dtf/delete/', dtf_delete, name="dtf_delete"),
    path('dtf/export_dtf_data/', export_dtf_data, name="export_dtf_data"),
    path('dtf/generic_dtf_data/', generic_dtf_data, name="generic_dtf_data"),
    path('dtf/add_array/', add_array, name="add_array"),
    path('dtf/import_arrays/', import_arrays, name="import_arrays"),
    path('dtf/dtf_dg_import/', dtf_data_group_import, name="dtf_dg_import"),
    path('dtf/dtf_dg_modbus_import/', dtf_data_group_modbus_import, name="dtf_dg_import_modbus"),
    path('dtf/delete_datagroup/', delete_datagroup, name="delete_datagroup"),
    ## TEMPLATES ##
    path('dds/mapping_template/', mapping_template, name="mapping_template"),
    path('dds/mapping_validation_template/', mapping_validation_template, name="mapping_validation_template"),
    path('dds/commands_template/', command_import_template, name="command_template"),
    path('dds/commands_validation_template/', command_validation_template, name="command_validation_template"),
    path('dds/facility_import_template/', facility_import_template, name="facility_import_template"),
]

projects/urls.py
from django.urls import path
from .views import *

app_name = 'projects'

urlpatterns = [
    path('<int:pk>/', ProjectDetailView.as_view(), name="main"),
    path('<int:pk>/management', BigtimeUpdate.as_view(), name="project_management"),
    path('long_desc/', update_long_descriptions, name="long_desc"),
    path('create_subs/', create_substitutions, name="create_subs"),
    path('add/', project_add, name="add"),
    path('templates/', export_template, name="templates"),
    path('galaxy_parse/', parse_galaxy, name="galaxy_parse"),
    path('create_comm_devs/', create_comm_devs, name="create_comm_devs"),
    path('add_bigtime_tasks/', add_bigtime_tasks, name="add_bigtime_tasks"),
    path('delete_bigtime_tasks/', delete_bigtime_tasks, name="delete_bigtime_tasks"),
]

files/models.py
from django.db import models
from django.conf import settings
from django.shortcuts import reverse

from projects.models import Project
import pandas as pd

import os

from cygdevices.device import DeviceDef
from cygdevices.dtf import DTF as D

from django.db.models.signals import pre_delete
from django.dispatch import receiver


# Create your models here.
class DDS(models.Model):
    file = models.FileField(upload_to='dds/')
    uploaded = models.DateTimeField(auto_now=True)
    last_update = models.DateTimeField(auto_now=True)
    project = models.ForeignKey(Project, on_delete=models.CASCADE)

    def __str__(self):
        return "{} - {}".format(self.project, self.file)

    @property
    def base_file(self):
        return os.path.basename(str(self.file))

    @property
    def export_url(self):
        return reverse("files:dds_export", kwargs={'id': self.pk})

    @property
    def xml(self):
        try:
            dds_xml = DeviceDef(self.file)
        except:
            print("DDS File not found at: {}".format(os.path.join(settings.MEDIA_URL, str(self.file))))
            return None
        return dds_xml

    def get_absolute_url(self):
        return reverse('files:dds', args=[str(self.pk)])

    def add_mappings(self, dtf_obj, excel, deid_only, add_dgs, dg_fac_type="point"):
        dtf_xml = dtf_obj.xml
        dds_xml = self.xml
        if dtf_xml is not None and dds_xml is not None:
            mappings = pd.read_excel(excel, sheet_name="Sheet1")
            error_log = dds_xml.mapping_excel_import(mappings, dtf_xml, deid_only, add_dgs, dg_fac_type)
        else:
            error_log = ["DDS or DTF File not found"]
        return error_log

    def add_commands(self, dtf_obj, excel, modbus):
        dtf_xml = dtf_obj.xml
        dds_xml = self.xml
        if dtf_xml is not None and dds_xml is not None:
            cmds = pd.read_excel(excel, sheet_name="Sheet1")
            error_log = dds_xml.import_commands(cmds, dtf_xml, modbus)
        else:
            error_log = ["DDS or DTF File not found"]
        return error_log

    def check_facilities(self, excel):
        facs_df = pd.read_excel(excel, sheet_name="Sheet1")
        facs = facs_df["facility"].to_list()
        dne = self.xml.fac_exists_check(facs)
        return dne

    def _validator(self, cmd, data, pnt_type, manual, tag):
        """
        Runs a series of checks on command to validate
            1. cmd_tag != tag => tagName in DTF matches command
            2. int(cmd["value"]) != int(data["val"]) => value of command is DDS matching command (do only)
            3. cmd["facility"] != data["fac"] or cmd["udc"] != data["udc"] => Manual entry point matches (manual only)
        :param cmd: singled command pandas row
        :param data: data fetched form device and dtf
        :param pnt_type: point type (ao or do)
        :param manual: manual entry bool
        :param tag: tagName from DTF
        :return: True if valid, False if invalid
        """
        reg = cmd["reg"].split(":")
        if len(reg) < 2:
            return False, "Invalid Reg"
        cmd_tag = "{}[{}]".format(reg[0], reg[1])
        if cmd_tag != tag:
            return False, "Wrong Reg"
        if pnt_type == "do":
            if int(cmd["value"]) != int(data["val"]):
                return False, "Wrong Cmd Value"
        if manual:
            if cmd["facility"] != data["fac"] or cmd["udc"] != data["udc"]:
                return False, "Wrong manual Update Pnt"
        return True, None

    def validate_cmds(self, cmd_data, dtf):
        """
        Validates commands by:
            1. Fetching command from device
            2. Fetching where the command is pointed to in dtf
            3. Comparing fetched data to supplied command (see _validator method)
        :param cmd_data: pandas df object from commands excel import
        :param dtf: dtf object
        :return: List of invalid commands
        """
        cmds = pd.read_excel(cmd_data, sheet_name="Sheet1")
        dds_xml = self.xml
        dtf_xml = dtf.xml
        errors = []
        for i, cmd in cmds.iterrows():
            manual = True if cmd["pointtype"] == "manual entry" else False
            pnt_type = cmd["cmd_type"]
            data = dds_xml.cmd_data(cmd["device"], cmd["command"], cmd["facility"], pnt_type, manual)
            if data is not None:
                tag = dtf_xml.deid_tagname(data["dg"], data["ld"])
                valid, err = self._validator(cmd, data, pnt_type, manual, tag)
                if not valid:
                    udc = str(cmd["udc"])
                    errors.append({
                        "device": cmd["device"],
                        "command": cmd["command"],
                        "fac": cmd["facility"],
                        "val": cmd["value"],
                        "dds_val": data["val"],
                        "udc": udc,
                        "dds_fac": data["udc"] if "udc" in data else "NONE",
                        "reg": cmd["reg"],
                        "dtf_reg": tag,
                        "err_msg": err
                    })
            else:
                udc = str(cmd["udc"])
                errors.append({
                    "device": cmd["device"],
                    "command": cmd["command"],
                    "fac": cmd["facility"],
                    "val": cmd["value"],
                    "dds_val": "NONE",
                    "udc": udc,
                    "dds_fac": "NONE",
                    "reg": "NONE",
                    "dtf_reg": "NONE",
                    "err_msg": "Cmd Not Found in Device"
                })
        return errors

    def validate_mappings(self, dtf_xml, pnts_data):
        pnts = pd.read_excel(pnts_data, sheet_name="Sheet1")
        pnts.set_index("point", inplace=True)
        log = self.xml.validate_mappings(dtf_xml, pnts)
        return log

    def import_facilites(self, fac_data):
        facs = pd.read_excel(fac_data, sheet_name="Sheet1")
        dds_xml = self.xml
        log = []
        for i, f in facs.iterrows():
            if "ordinal" in f:
                outcome = dds_xml.add_facility(f["facility"], f["device"], f["ordinal"])
            else:
                outcome = dds_xml.add_facility(f["facility"], f["device"])
            log.append({"outcome": outcome})
        dds_xml.save()
        return log

    def save_document(self):
        self.xml.save()


@receiver(pre_delete, sender=DDS)
def dds_pre_delete(sender, instance, **kwargs):
    instance.xml.delete()


class DTF(models.Model):
    file = models.FileField(upload_to="dtf/")
    uploaded = models.DateTimeField(auto_now=True)
    project = models.ForeignKey(Project, on_delete=models.CASCADE)

    def __str__(self):
        return "{} - {}".format(self.project, self.file)

    @property
    def xml(self):
        try:
            dtf_xml = D(self.file)
        except:
            print("DTF File not found at: {}".format(os.path.join(settings.MEDIA_URL, str(self.file))))
            return None
        return dtf_xml

    @property
    def base_file(self):
        return os.path.basename(str(self.file))

    @property
    def export_url(self):
        return reverse("files:dtf_export", kwargs={'id': self.pk})

    def get_absolute_url(self):
        return reverse('files:dtf', args=[str(self.pk)])

    def import_datagroups(self, excel_data, reg_gap, modbus=False):
        dgs_data = pd.read_excel(excel_data, sheet_name="Sheet1", converters={"bit": str})
        return self.xml.import_datagroups(dgs_data, reg_gap, modbus)


@receiver(pre_delete, sender=DTF)
def dtf_pre_delete(sender, instance, **kwargs):
    instance.xml.delete()


class ScreenSubstitutions(models.Model):
    file = models.FileField(upload_to="dtf/")
    uploaded = models.DateTimeField(auto_now=True)
    project = models.ForeignKey(Project, on_delete=models.CASCADE)

    def __str__(self):
        return "{} - {}".format(self.project, self.file)

    @property
    def base_file(self):
        return os.path.basename(str(self.file))

projects/models.py
from django.db import models
from django.shortcuts import reverse
from django.contrib.auth.models import User

from projman import DevopsData, BigTime
from projman.devops.utils import parse_tiga_id
from cygnet.settings import DEVOPS_TOKEN, BIGTIME_TOKEN, BIGTIME_FIRM_KEY

# Create your models here.
class Project(models.Model):
    name = models.CharField(max_length=124)
    devops_name = models.CharField(max_length=124, null=True)
    tiga_id = models.CharField(max_length=10, null=True)
    members = models.ManyToManyField(User, blank=True)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('projects:main', args=[str(self.id)])

    def check_user(self, user):
        if user in self.members:
            return True
        else:
            return False

    def bigtime_devops_sync(self):
        devops_api = DevopsData(DEVOPS_TOKEN)
        bigtime_api = BigTime(BIGTIME_TOKEN, BIGTIME_FIRM_KEY)
        project_features = devops_api.project_features(self.devops_name)
        task_breakdown = devops_api.get_task_with_service_disciplines(self.devops_name,
                                                                      parse_tiga_id(self.devops_name),
                                                                      project_features)
        bigtime_tasks, bigtime_id = bigtime_api.task_breakdown_from_tiga_id(parse_tiga_id(self.devops_name))
        for service, tasks in task_breakdown.items():
            if service in bigtime_tasks:
                for task in tasks:
                    task["in_bigtime"] = True if task["task_id"] in bigtime_tasks[service]["ids"] else False
            else:
                for task in tasks:
                    task["in_bigtime"] = False
        return {"task_breakdown": task_breakdown, "bigtime_tasks": bigtime_tasks, "bigtime_id": bigtime_id}

projects/forms.py
from django import forms
from .models import Project


class ProjectForm(forms.ModelForm):
    class Meta:
        model = Project
        fields = ('name',)

projects/templates/projects/management.html
{% extends 'base.html' %}
{% block body_block %}
<div class="container" style="width: 100%; margin: 0px; max-width: 100%; text-align: center;">
    <div class="row" >
        <h1 class="mx-auto my-3">{{ project.name }}</h1>
    </div>
    {% if task_breakdown %}
    <div class="row">
        <div class="col-sm-6">
            <div class="card text-center">
                <div class="card-header">
                    DevOps Task Breakdown
                </div>
                <form action="{% url 'projects:add_bigtime_tasks' %}" method="POST">{% csrf_token %}
                    <div class="card-body">
                        <input type="hidden" name="bigtime_id" value="{{ bigtime_id }}">
                        {% if task_breakdown %}
                        {% for key, values in task_breakdown.items %}
                        <h5 class="card-title">{{ key }}</h5>
                        {% for task in values %}
                        <div class="form-check card-text">
                            {% if not task.in_bigtime %}
                            <input class="form-check-input" type="checkbox" id="task{{ forloop.counter }}_{{ key }}"
                                   name="task{{ forloop.counter }}_{{ key }}" value="{{ task.task_name }}">
                            {% endif %}
                            <label class="form-check-label" for="task{{ forloop.counter }}_{{ key }}">
                                ID: {{ task.task_id }} Name: {{ task.task_name }}
                            </label>
                        </div>
                        {% endfor %}
                        {% endfor %}
                        {% endif %}
                    </div>
                    <div class="card-footer text-muted">
                        <button class="btn btn-primary" type="submit">Create BigTime Tasks</button>
                    </div>
                </form>
            </div>
        </div>
        <div class="col-sm-6">
            <div class="card text-center">
                <div class="card-header">
                    BigTime Task Breakdown
                </div>
                <form action="{% url 'projects:delete_bigtime_tasks' %}" method="POST">{% csrf_token %}
                    <div class="card-body">
                        <input type="hidden" name="bigtime_id" value="{{ bigtime_id }}">
                        {% if bigtime_tasks %}
                        {% for k, values in bigtime_tasks.items %}
                        <h5 class="card-title">{{ k }}</h5>
                        {% for task in values.detailed %}
                        <div class="form-check card-text">
                            <input class="form-check-input" type="checkbox" id="task{{ forloop.counter }}_{{ k }}"
                                   name="task{{ forloop.counter }}_{{ k }}" value="{{ task.task_id }}">
                            <label class="form-check-label" for="task{{ forloop.counter }}_{{ k }}">
                                {{ task.name }}
                            </label>
                        </div>
                        {% endfor %}
                        {% endfor %}
                        {% endif %}
                    </div>
                    <div class="card-footer text-muted">
                        <button class="btn btn-primary" type="submit">Delete BigTime Tasks</button>
                    </div>
                </form>
            </div>
        </div>
    </div>
    {% else %}
    <h3>Please add DevOps Project Name to Project!</h3>
    {% endif %}
</div>
{% endblock %}

projects/templates/projects/project_detail.html
{% extends 'base.html' %}
{% block body_block %}
<div class="container" style="width: 100%; margin: 0px; max-width: 100%; text-align: center;">
    <h1>{{ project.name }}</h1>
<!--    <div class="row">-->
<!--        <div class="col file-container">-->
<!--            <h2>DDS</h2>-->
<!--            <div id="dds-form" style="float: left; width: 100%; margin: 10px;">-->
<!--                <h4>Upload DDS</h4>-->
<!--                <form method="post" enctype="multipart/form-data" action="{% url 'files:dds_upload' %}">-->
<!--                    {% csrf_token %}-->
<!--                    {{ dds_form }}-->
<!--                    <input type="hidden" name="next" value="{{ request.path }}">-->
<!--                    <button type="submit">Upload</button>-->
<!--                </form>-->
<!--            </div>-->
<!--            <div style="margin-top: 50px;">-->
<!--                {% include 'projects/snippets/file_table.html' with files=project.dds_set.all dds=True %}-->
<!--            </div>-->
<!--        </div>-->
<!--        <div class="col file-container">-->
<!--            <h2>DTF</h2>-->
<!--            <div id="dtf-form" style="float: left; width: 100%; margin: 10px;">-->
<!--                <h4>Upload DTF</h4>-->
<!--                <form method="post" enctype="multipart/form-data" action="{% url 'files:dtf_upload' %}">-->
<!--                    {% csrf_token %}-->
<!--                    {{ dtf_form }}-->
<!--                    <input type="hidden" name="next" value="{{ request.path }}">-->
<!--                    <button type="submit">Upload</button>-->
<!--                </form>-->
<!--            </div>-->
<!--            <br>-->
<!--            <div style="margin-top: 50px;">-->
<!--                {% include 'projects/snippets/file_table.html' with files=project.dtf_set.all dtf=True %}-->
<!--            </div>-->
<!--        </div>-->
<!--    </div>-->

    <div class="row">
        <div class="col-sm-6">
            <div class="card text-center">
                <div class="card-header">
                    DDS
                </div>
                <div class="card-body">
                    <h5 class="card-title">Upload DDS</h5>
                    <div class="card-text">
                        <div id="dds-form">
                            <form method="post" enctype="multipart/form-data" action="{% url 'files:dds_upload' %}">
                                {% csrf_token %}
                                {{ dds_form }}
                                <input type="hidden" name="next" value="{{ request.path }}">
                                <button type="submit">Upload</button>
                            </form>
                        </div>
                        <div style="margin-top: 25px;">
                            {% include 'projects/snippets/file_table.html' with files=project.dds_set.all dds=True %}
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="col-sm-6">
            <div class="card text-center">
                <div class="card-header">
                    DTF Template
                </div>
                <div class="card-body">
                    <h5 class="card-title">Upload DTF</h5>
                    <div class="card-text">
                        <div id="dtf-form">
                            <form method="post" enctype="multipart/form-data" action="{% url 'files:dtf_upload' %}">
                                {% csrf_token %}
                                {{ dtf_form }}
                                <input type="hidden" name="next" value="{{ request.path }}">
                                <button type="submit">Upload</button>
                            </form>
                        </div>
                        <div style="margin-top: 25px;">
                            {% include 'projects/snippets/file_table.html' with files=project.dtf_set.all dtf=True %}
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <div class="row">
        <div class="col util-container">
            <div class="project-util">
                <form method="POST" enctype="multipart/form-data" action="{% url 'projects:long_desc' %}">
                    {% csrf_token %}
                    <h3>Long Description Change</h3><br>
                    <label>Points Export as ".xlsx" file</label><br>
                    <input type="file" name="points"><br>
                    <input hidden name="dds-id" value="{{ dds.pk }}">
                    <button type="submit">Update Long Descriptions</button>
                </form>
            </div>
            <div class="project-util">
                <form method="POST" enctype="multipart/form-data" action="{% url 'projects:create_subs' %}">
                    {% csrf_token %}
                    <h3>Create Substitution XML</h3>
                    <a href="{% url 'projects:templates' %}?file=subs">Download Template</a><br>
                    <label>Substitutions Excel</label><br>
                    <input type="file" name="subs"><br>
                    <button type="submit">Create Substitutions</button>
                </form>
            </div>
            <div class="project-util">
                <form method="POST" enctype="multipart/form-data" action="{% url 'projects:create_comm_devs' %}">
                    {% csrf_token %}
                    <h3>Create Bulk CygNet Comm Devices</h3>
                    <a href="{% url 'projects:templates' %}?file=commdevs">Download Template</a><br>
                    <label>Substitutions Excel</label><br>
                    <input type="file" name="commdevs"><br>
                    <button type="submit">Create Devices</button>
                </form>
            </div>
            <div class="project-util">
                <form method="POST" enctype="multipart/form-data" action="{% url 'projects:galaxy_parse' %}">
                    {% csrf_token %}
                    <h3>Parse Galaxy Dump</h3>
                    <label>Parse Galaxy Dump</label><br>
                    <input type="file" name="galaxy"><br>
                    <div class="form-check">
                        <input class="form-check-input" type="radio" name="parseType" id="full" value="full" checked>
                        <label class="form-check-label" for="full">
                            Full Parse
                        </label>
                    </div>
                    <div class="form-check">
                        <input class="form-check-input" type="radio" name="parseType" id="regonly" value="regonly">
                        <label class="form-check-label" for="regonly">
                            Register and Source Info Only
                        </label>
                    </div>
                    <div class="form-check">
                        <input class="form-check-input" type="radio" name="parseType" id="scaling" value="scaling">
                        <label class="form-check-label" for="scaling">
                            Scaling Only
                        </label>
                    </div>
                    <button type="submit">Parse</button>
                </form>
            </div>
        </div>
    </div>
</div>
{% endblock %}