cygnet/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from projects.views import index, user_login, user_logout

urlpatterns = [
    path('admin/', admin.site.urls),
    path('files/', include('files.urls', namespace='files')),
    path('projects/', include('projects.urls', namespace='projects')),
    path('', index, name="home"),
    path('login/', user_login, name="login"),
    path('logout/', user_logout, name="logout")
]
if settings.DEBUG:
    urlpatterns = urlpatterns + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns = urlpatterns + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

files/urls.py
from django.urls import path
from .views import *

app_name = 'files'

urlpatterns = [
    ## Files ##
    path('upload', upload, name='upload'),
    path('dds_upload', dds_upload, name='dds_upload'),
    path('dtf_upload', dtf_upload, name='dtf_upload'),
    ## DDS ##
    path('dds/<int:pk>/', DDSDetailView.as_view(), name="dds"),
    path('dds/export/', export_dds, name="dds_export"),
    path('dds/dds_mappings_export/', mapping_export, name="dds_mappings_export"),
    path('dds/export_cmds/', mapping_export_with_regs, name="export_cmds"),
    path('dds/dds_add_mappings/', dds_add_mapping, name="dds_add_mappings"),
    path('dds/dds_add_commands/', dds_add_commands, name="dds_add_commands"),
    path('dds/correct_dec_check/', correct_device_check, name="correct_dec_check"),
    path('dds/unmapped_facs/', unmapped_facs, name="unmapped_facs"),
    path('dds/orphans/', find_orphans, name="orphans"),
    path('dds/fac_exist/', facs_dne, name="fac_exist"),
    path('dds/validate_commands/', validate_commands, name="validate_commands"),
    path('dds/get_mappings/', get_mappings, name="get_mappings"),
    path('dds/delete/', dds_delete, name="dds_delete"),
    path('dds/validate_maps/', validate_mappings, name="validate_maps"),
    path('dds/import_facs/', import_facs, name="import_facs"),
    ## DTF ##
    path('dtf/<int:pk>/', DTFDetailView.as_view(), name="dtf"),
    path('dtf/export/', export_dtf, name='dtf_export'),
    path('dtf/unused_deids/', unmapped_dieds, name="unused_dieds"),
    path('dtf/delete/', dtf_delete, name="dtf_delete"),
    path('dtf/export_dtf_data/', export_dtf_data, name="export_dtf_data"),
    path('dtf/generic_dtf_data/', generic_dtf_data, name="generic_dtf_data"),
    path('dtf/add_array/', add_array, name="add_array"),
    path('dtf/import_arrays/', import_arrays, name="import_arrays"),
    path('dtf/dtf_dg_import/', dtf_data_group_import, name="dtf_dg_import"),
    path('dtf/dtf_dg_modbus_import/', dtf_data_group_modbus_import, name="dtf_dg_import_modbus"),
    path('dtf/delete_datagroup/', delete_datagroup, name="delete_datagroup"),
    ## TEMPLATES ##
    path('dds/mapping_template/', mapping_template, name="mapping_template"),
    path('dds/mapping_validation_template/', mapping_validation_template, name="mapping_validation_template"),
    path('dds/commands_template/', command_import_template, name="command_template"),
    path('dds/commands_validation_template/', command_validation_template, name="command_validation_template"),
    path('dds/facility_import_template/', facility_import_template, name="facility_import_template"),
]

projects/urls.py
from django.urls import path
from .views import *

app_name = 'projects'

urlpatterns = [
    path('<int:pk>/', ProjectDetailView.as_view(), name="main"),
    path('<int:pk>/management', BigtimeUpdate.as_view(), name="project_management"),
    path('long_desc/', update_long_descriptions, name="long_desc"),
    path('create_subs/', create_substitutions, name="create_subs"),
    path('add/', project_add, name="add"),
    path('templates/', export_template, name="templates"),
    path('galaxy_parse/', parse_galaxy, name="galaxy_parse"),
    path('create_comm_devs/', create_comm_devs, name="create_comm_devs"),
    path('add_bigtime_tasks/', add_bigtime_tasks, name="add_bigtime_tasks"),
    path('delete_bigtime_tasks/', delete_bigtime_tasks, name="delete_bigtime_tasks"),
]

templates/base.html
<!DOCTYPE html>
<html lang="en">
{% load static %}
<head>
    <meta charset="UTF-8">
    <title>TIGA Utilities</title>
    <link rel="icon" type="image/x-icon" href="{% static 'images/favicon.ico' %}">
    {% include 'base/css.html' %}

</head>
<body>
<nav class="navbar navbar-expand-lg navbar-dark bg-dark static-top">
    <div class="container">
        <a class="navbar-brand" href="#"><img src="{% static 'images/tiga.png' %}" alt=""></a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive"
                aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav mr-auto">
                <li>
                    <a class="nav-link" href="/">Home</a>
                </li>
                {% if project %}
                <li class="nav-item">
                    <a class="nav-link" href="{{ project.get_absolute_url }}">Project</a>
                </li>
                {% if request.user.is_superuser %}
                <li class="nav-item">
                    <a class="nav-link" href="{{ project.get_absolute_url }}management">Project Management</a>
                </li>
                {% endif %}
                {% endif %}
            </ul>
        </div>
        {% if user.is_authenticated %}
        <div class="dropdown dropleft">
            <button class="btn btn-primary btn-sm dropdown-toggle" type="button" id="dropdownMenuButton"
                    data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                {{ user.username }}
            </button>
            <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
                <a class="dropdown-item" href="{% url 'logout' %}">Logout</a>
            </div>
        </div>
        {{% else %}
        <a class="btn btn-primary btn-sm" type="submit" href="/login">Login</a>
        {% endif %}
    </div>
</nav>
<nav class="navbar sticky-top navbar-light bg-light">
  Maintained By Joe Ballard (joseph.ballard@tiga.us)
</nav>
{% block body_block %}


{% endblock %}

{% include 'base/js.html' %}

<script>

</script>
</body>

</html>

templates/index.html
{% extends 'base.html' %}
{% block body_block %}
<body>
<div class="container">
    {% if user.is_staff %}
    <div class="row" style="margin:10px">
        <form method="POST" action="{% url 'projects:add' %}">
            <div class="form-group">
                <h2>Create Project</h2>
                {% csrf_token %}
                {{ form.as_p }}
            </div>
            <button type="submit" class="btn btn-primary">Create</button>
        </form>
    </div>
    {% endif %}
    <div class="row" style="margin-top: 50px">
        <div class="card text-center">
            <div class="card-header">
                Your Projects
            </div>
            <div class="card-body">
                <div class="list-group">
                    {% if projects %}
                    {% for p in projects %}
                    <a href="{{ p.get_absolute_url }}" class="list-group-item list-group-item-action">{{ p }}</a>
                    {% endfor %}
                    {% endif %}
                </div>
            </div>
        </div>

    </div>
</div>
</body>
{% endblock %}

templates/login.html
{% extends 'base.html' %}
{% block body_block %}
<div class="container login-container">
    <div class="row">
        <div class="col-md-6 login-form-2">
            <h3>Please Login</h3>
            <form action="{% url 'login' %}" method="POST">
                {% csrf_token %}
                <div class="form-group">
                    <input type="text" class="form-control" placeholder="USERNAME" value="" name="username"/>
                </div>
                <div class="form-group">
                    <input type="password" class="form-control" placeholder="PASSWORD" value="" name="password"/>
                </div>
                <div class="form-group">
                    <input type="submit" class="btnSubmit" value="Login"/>
                </div>
            </form>
        </div>
    </div>
</div>
{% endblock %}